### ISSUE TITLE
Not working after install

### ISSUE THREAD

**Issue by Iwhite67** [konsumer/tplink-lightbulb#27]
Hello, i have make a npm install on my raspi, i have LB130 on same network buty when i make a tplight scan or tplight on -h, he send a error

pi@Raspberry-Ebot:~ $ tplight scan
/usr/lib/node_modules/tplink-lightbulb/node_modules/yargs/index.js:5
const yargs = require('./yargs')
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/lib/node_modules/tplink-lightbulb/build/cli.js:1                                                                                                                                                             7:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

pi@Raspberry-Ebot:~ $ tplight on -h
/usr/lib/node_modules/tplink-lightbulb/node_modules/yargs/index.js:5
const yargs = require('./yargs')
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/lib/node_modules/tplink-lightbulb/build/cli.js:1                                                                                                                                                             7:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by konsumer** [comment]
Update your version of nodejs. It's saying it doesn't like `const` without `use strict`, which is a hting that happens in very old versions of nodejs.

Read [here](http://thisdavej.com/upgrading-to-more-recent-versions-of-node-js-on-the-raspberry-pi/) for more info.

**Comment by Iwhite67** [comment]
ty
