### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by nolageek** [konsumer/tplink-lightbulb#57]
I'm getting this error on Windows 10:

C:\Users\streaming\Downloads\win-x64\win-x64>tplight.exe scan
pkg/prelude/bootstrap.js:1320
      return wrapper.apply(this.exports, args);
                     ^

ReferenceError: regeneratorRuntime is not defined
    at C:\snapshot\tplink-lightbulb\build\cli.js
    at Object.<anonymous> (C:\snapshot\tplink-lightbulb\build\cli.js)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1218:10)
    at Module.load (internal/modules/cjs/loader.js:1047:32)
    at Function.Module._load (internal/modules/cjs/loader.js:935:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1375:12)
    at internal/main/run_main_module.js:17:47

**Comment by konsumer** [comment]
Hmm, I think this is related to how the cli runtime is compiled. I will look into it. It generally means babel is messed up.

**Comment by konsumer** [comment]
I updated [the last release](https://github.com/konsumer/tplink-lightbulb/releases/tag/v1.6.2), but I don't have a win-box to test right now, so try it out and let me know if it works.

**Comment by konsumer** [comment]
Without more input, I'm going to close this. Lemme know if it's not working.
